import React from 'react'
import MyCrossword from 'mycrossword';
import 'mycrossword/dist/index.css';
import { useHistory } from 'react-router';


export default function Crossword({pays}) {

    console.log("payspays", pays)
    let data

    if(pays === "Anglais"){
      data = dataEN
    }
    else if (pays === "Français"){
      data = dataFR
    }
    else if (pays === "Allemand") {
      data = dataAL
    }
    else if (pays === "Espagnol") {
      data = dataES
    }

    let history = useHistory()
    function handleClickBack(){
        history.push({
            pathname : "/ateliers",
        })

    }

    return (
        <div className="container">
          <div className="row text-center">
            <div className="col my-3 colortitle4 rounded">
              <h1 className="text-white align-middle">Mot croisé</h1>
            </div>
          </div>
          <div className="row">
              <div className="col text-center pt-5">
                  <MyCrossword id="crossword-1" data={data} theme='orange' />
              </div>
          </div>
          <div className="row">
              <button
                className="btn btn-primary"
                onClick={() => {
                  if (window.confirm("Voulez-vous vraiment retourner à la page ateliers ?")) {
                    handleClickBack()
                  }
                }}
              >Retour à la page ateliers</button>
          </div>

        </div>
    
    );
}

const dataFR = {
  id: 'simple/1',
  number: 1,
  name: 'Simple Crossword #1',
  date: 1542326400000,
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'Un légume qui se transforme en carrosse pour Cendrillon',
      direction: 'across',
      length: 10,
      group: ['1-across'],
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: 'CITROUILLE',
    },
    {
      id: '2.1-across',
      number: 2.1,
      humanNumber: '2.1',
      clue: 'Un désodorisant, c’est fait pour masquer les mauvaises...',
      direction: 'across',
      length: 6,
      group: ['2.1-across'],
      position: { x: 0, y: 1 },
      separatorLocations: {},
      solution: 'ODEURS',
    },
    {
      id: '2.2-across',
      number: 2.2,
      humanNumber: '2.2',
      clue: 'Un liquide indispensable à la vie',
      direction: 'across',
      length: 3,
      group: ['2.2-across'],
      position: { x: 7, y: 1 },
      separatorLocations: {},
      solution: 'EAU',
    },
    {
      id: '3.1-across',
      number: 3.1,
      humanNumber: '3.1',
      clue: 'Adjectif démonstratif',
      direction: 'across',
      length: 2,
      group: ['3.1-across'],
      position: { x: 0, y: 2 },
      separatorLocations: {},
      solution: 'CE',
    },
    {
      id: '3.2-across',
      number: 3.2,
      humanNumber: '3.2',
      clue: 'Au-dessus du rez-de-chaussée, c’est le premier...',
      direction: 'across',
      length: 5,
      group: ['3.2-across'],
      position: { x: 5, y: 2 },
      separatorLocations: {},
      solution: 'ETAGE',
    },
    {
      id: '4-across',
      number: 4,
      humanNumber: '4',
      clue: 'Très connu',
      direction: 'across',
      length: 7,
      group: ['4-across'],
      position: { x: 0, y: 3 },
      separatorLocations: {},
      solution: 'CELEBRE',
    },
    {
      id: '5-across',
      number: 5,
      humanNumber: '5',
      clue: 'Coupe la laine des mouton',
      direction: 'across',
      length: 4,
      group: ['5-across'],
      position: { x: 6, y: 4 },
      separatorLocations: {},
      solution: 'TOND',
    },
    {
      id: '6.1-across',
      number: 6.1,
      humanNumber: '6.1',
      clue: 'Jour de fête et de cadeaux',
      direction: 'across',
      length: 4,
      group: ['6.1-across'],
      position: { x: 0, y: 5 },
      separatorLocations: {},
      solution: 'NOEL',
    },
    {
      id: '6.2-across',
      number: 6.2,
      humanNumber: '6.2',
      clue: 'Fait la liaison entre deux parties d’une phrase',
      direction: 'across',
      length: 2,
      group: ['6.2-across'],
      position: { x: 6, y: 5 },
      separatorLocations: {},
      solution: 'ET',
    },
    {
      id: '7.1-across',
      number: 7.1,
      humanNumber: '7.1',
      clue: 'Atteint de la rage',
      direction: 'across',
      length: 6,
      group: ['7.1-across'],
      position: { x: 0, y: 6 },
      separatorLocations: {},
      solution: 'ENRAGE',
    },
    {
      id: '7.2-across',
      number: 7.2,
      humanNumber: '7.2',
      clue: 'Personne : il n’y a pas ... qui vive',
      direction: 'across',
      length: 3,
      group: ['7.2-across'],
      position: { x: 7, y: 6 },
      separatorLocations: {},
      solution: 'AME',
    },
    {
      id: '8-across',
      number: 8,
      humanNumber: '8',
      clue: 'Complètement stupéfaits',
      direction: 'across',
      length: 6,
      group: ['8-across'],
      position: { x: 4, y: 7 },
      separatorLocations: {},
      solution: 'AHURIS',
    },
    {
      id: '9.1-across',
      number: 9.1,
      humanNumber: '9.1',
      clue: 'Toute petite lumière',
      direction: 'across',
      length: 5,
      group: ['9.1-across'],
      position: { x: 0, y: 8 },
      separatorLocations: {},
      solution: 'LUEUR',
    },
    {
      id: '9.2-across',
      number: 9.2,
      humanNumber: '9.2',
      clue: 'Négation',
      direction: 'across',
      length: 2,
      group: ['9.2-across'],
      position: { x: 6, y: 8 },
      separatorLocations: {},
      solution: 'NI',
    },
    {
      id: '10.1-across',
      number: 10.1,
      humanNumber: '10.1',
      clue: 'Dans',
      direction: 'across',
      length: 2,
      group: ['10.1-across'],
      position: { x: 0, y: 9 },
      separatorLocations: {},
      solution: 'EN',
    },
    {
      id: '10.2-across',
      number: 10.2,
      humanNumber: '10.2',
      clue: 'Je me suis moqué d’elle devant tout le monde, maintenant elle est ...',
      direction: 'across',
      length: 5,
      group: ['10.2-across'],
      position: { x: 3, y: 9 },
      separatorLocations: {},
      solution: 'VEXEE',
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      clue: 'Rouge à points noirs, on l’appelle la "bête à bon Dieu"',
      direction: 'down',
      length: 10,
      group: ['1-down'],
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: 'COCCINELLE',
    },
    {
      id: '2.1-down',
      number: 2.1,
      humanNumber: '2.1',
      clue: 'Pensée',
      direction: 'down',
      length: 4,
      group: ['2.1-down'],
      position: { x: 1, y: 0 },
      separatorLocations: {},
      solution: 'IDEE',
    },
    {
      id: '2.2-down',
      number: 2.2,
      humanNumber: '2.2',
      clue: 'Pronom indéfini',
      direction: 'down',
      length: 2,
      group: ['2.2-down'],
      position: { x: 1, y: 5 },
      separatorLocations: {},
      solution: 'ON',
    },
    {
      id: '2.3-down',
      number: 2.3,
      humanNumber: '2.3',
      clue: 'Chiffre proche de zéro',
      direction: 'down',
      length: 2,
      group: ['2.3-down'],
      position: { x: 1, y: 8 },
      separatorLocations: {},
      solution: 'UN',
    },
    {
      id: '3.1-down',
      number: 3.1,
      humanNumber: '3.1',
      clue: 'Pronom personnel',
      direction: 'down',
      length: 2,
      group: ['3.1-down'],
      position: { x: 2, y: 0, },
      separatorLocations: {},
      solution: 'TE',
    },
    {
      id: '3.2-down',
      number: 3.2,
      humanNumber: '3.2',
      clue: 'Plante qui grimpe le long des murs',
      direction: 'down',
      length: 6,
      group: ['3.2-down'],
      position: { x: 2, y: 3, },
      separatorLocations: {},
      solution: 'LIERRE',
    },
    {
      id: '4.1-down',
      number: 4.1,
      humanNumber: '4.1',
      clue: ' ... comme un renard',
      direction: 'down',
      length: 4,
      group: ['4.1-down'],
      position: { x: 3, y: 0, },
      separatorLocations: {},
      solution: 'RUSE',
    },
    {
      id: '4.2-down',
      number: 4.2,
      humanNumber: '4.2',
      clue: 'Note de musique',
      direction: 'down',
      length: 2,
      group: ['4.2-down'],
      position: { x: 3, y: 5, },
      separatorLocations: {},
      solution: 'LA',
    },
    {
      id: '4.3-down',
      number: 4.3,
      humanNumber: '4.3',
      clue: 'Des rayons du soleil contre lesquels il faut se protéger',
      direction: 'down',
      length: 2,
      group: ['4.3-down'],
      position: { x: 3, y: 8, },
      separatorLocations: {},
      solution: 'UV',
    },
    {
      id: '5.1-down',
      number: 5.1,
      humanNumber: '5.1',
      clue: 'Métal jaune',
      direction: 'down',
      length: 2,
      group: ['5.1-down'],
      position: { x: 4, y: 0, },
      separatorLocations: {},
      solution: 'OR',
    },
    {
      id: '5.2-down',
      number: 5.2,
      humanNumber: '5.2',
      clue: 'C’est là qu’on prend le train',
      direction: 'down',
      length: 4,
      group: ['5.2-down'],
      position: { x: 4, y: 6, },
      separatorLocations: {},
      solution: 'GARE',
    },
    {
      id: '6.1-down',
      number: 6.1,
      humanNumber: '6.1',
      clue: 'Abimer',
      direction: 'down',
      length: 4,
      group: ['6.1-down'],
      position: { x: 5, y: 0, },
      separatorLocations: {},
      solution: 'USER',
    },
    {
      id: '6.2-down',
      number: 6.2,
      humanNumber: '6.2',
      clue: '... toi ! Viens ici',
      direction: 'down',
      length: 2,
      group: ['6.2-down'],
      position: { x: 5, y: 6, },
      separatorLocations: {},
      solution: 'EH',
    },
    {
      id: '7.1-down',
      number: 7.1,
      humanNumber: '7.1',
      clue: ' 0 + 0 = la .... à Toto',
      direction: 'down',
      length: 4,
      group: ['7.1-down'],
      position: { x: 6, y: 2, },
      separatorLocations: {},
      solution: 'TETE',
    },
    {
      id: '7.2-down',
      number: 7.2,
      humanNumber: '7.2',
      clue: 'La première page du journal',
      direction: 'down',
      length: 3,
      group: ['7.2-down'],
      position: { x: 6, y: 7, },
      separatorLocations: {},
      solution: 'UNE',
    },
    {
      id: '8.1-down',
      number: 8.1,
      humanNumber: '8.1',
      clue: 'Prénom féminin',
      direction: 'down',
      length: 3,
      group: ['8.1-down'],
      position: { x: 7, y: 0, },
      separatorLocations: {},
      solution: 'LEA',
    },
    {
      id: '8.2-down',
      number: 8.2,
      humanNumber: '8.2',
      clue: 'Une sorte de phoque qu’on voit dans les cirques',
      direction: 'down',
      length: 6,
      group: ['8.2-down'],
      position: { x: 7, y: 4, },
      separatorLocations: {},
      solution: 'OTARIE',
    },
    {
      id: '9.1-down',
      number: 9.1,
      humanNumber: '9.1',
      clue: 'Le bord de mer dans les iles du Pacifique',
      direction: 'down',
      length: 5,
      group: ['9.1-down'],
      position: { x: 8, y: 0, },
      separatorLocations: {},
      solution: 'LAGON',
    },
    {
      id: '9.2-down',
      number: 9.2,
      humanNumber: '9.2',
      clue: 'Note de musique',
      direction: 'down',
      length: 2,
      group: ['9.2-down'],
      position: { x: 8, y: 6, },
      separatorLocations: {},
      solution: 'MI',
    },
    {
      id: '10.1-down',
      number: 10.1,
      humanNumber: '10.1',
      clue: 'Obtenue',
      direction: 'down',
      length: 3,
      group: ['10.1-down'],
      position: { x: 9, y: 0, },
      separatorLocations: {},
      solution: 'EUE',
    },
    {
      id: '10.2-down',
      number: 10.2,
      humanNumber: '10.2',
      clue: 'A la station service, on choisit entre ...... ou essence',
      direction: 'down',
      length: 6,
      group: ['10.2-down'],
      position: { x: 9, y: 4, },
      separatorLocations: {},
      solution: 'DIESEL',
    },
  ],
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: {
    cols: 13,
    rows: 13,
  },
  crosswordType: 'quick',
};

const dataEN = {
  id: 'simple/1',
  number: 1,
  name: 'Simple Crossword #1',
  date: 1542326400000,
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'Cambrioleur',
      direction: 'across',
      length: 7,
      group: ['1-across'],
      position: { x: 2, y: 0 },
      separatorLocations: {},
      solution: 'BURGLAR',
    },
    {
      id: '2-across',
      number: 2,
      humanNumber: '2',
      clue: 'Voiture',
      direction: 'across',
      length: 3,
      group: ['2-across'],
      position: { x: 0, y: 1 },
      separatorLocations: {},
      solution: 'CAR',
    },
    {
      id: '3-across',
      number: 3,
      humanNumber: '3',
      clue: 'Lent',
      direction: 'across',
      length: 4,
      group: ['3-across'],
      position: { x: 7, y: 2 },
      separatorLocations: {},
      solution: 'SLOW',
    },
    {
      id: '4-across',
      number: 4,
      humanNumber: '4',
      clue: 'Fromage',
      direction: 'across',
      length: 6,
      group: ['4-across'],
      position: { x: 0, y: 4 },
      separatorLocations: {},
      solution: 'CHEESE',
    },
    {
      id: '5-across',
      number: 5,
      humanNumber: '5',
      clue: 'Congelée',
      direction: 'across',
      length: 6,
      group: ['5-across'],
      position: { x: 5, y: 5 },
      separatorLocations: {},
      solution: 'FROZEN',
    },
    {
      id: '6-across',
      number: 6,
      humanNumber: '6',
      clue: 'Plus grand',
      direction: 'across',
      length: 7,
      group: ['6-across'],
      position: { x: 1, y: 8 },
      separatorLocations: {},
      solution: 'BIGGEST',
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      clue: 'Cassé',
      direction: 'down',
      length: 6,
      group: ['1-down'],
      position: { x: 2, y: 0 },
      separatorLocations: {},
      solution: 'BROKEN',
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      clue: 'Poussin',
      direction: 'down',
      length: 5,
      group: ['2-down'],
      position: { x: 0, y: 1 },
      separatorLocations: {},
      solution: 'CHICK',
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      clue: 'Singe',
      direction: 'down',
      length: 6,
      group: ['3-down'],
      position: { x: 9, y: 1, },
      separatorLocations: {},
      solution: 'MONKEY',
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      clue: 'Avant',
      direction: 'down',
      length: 6,
      group: ['4-down'],
      position: { x: 5, y: 3, },
      separatorLocations: {},
      solution: 'BEFORE',
    },
    {
      id: '5-down',
      number: 5,
      humanNumber: '5',
      clue: 'Monstre',
      direction: 'down',
      length: 7,
      group: ['5-down'],
      position: { x: 7, y: 4, },
      separatorLocations: {},
      solution: 'MONSTER',
    },
    {
      id: '6-down',
      number: 6,
      humanNumber: '6',
      clue: 'Bébé',
      direction: 'down',
      length: 4,
      group: ['6-down'],
      position: { x: 1, y: 6, },
      separatorLocations: {},
      solution: 'BABY',
    },
    {
      id: '7-down',
      number: 7,
      humanNumber: '7',
      clue: 'Chien',
      direction: 'down',
      length: 3,
      group: ['7-down'],
      position: { x: 3, y: 6, },
      separatorLocations: {},
      solution: 'DOG',
    },
  ],
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: {
    cols: 13,
    rows: 13,
  },
  crosswordType: 'quick',
};

const dataAL = {
  id: 'simple/1',
  number: 1,
  name: 'Simple Crossword #1',
  date: 1542326400000,
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'Rvière',
      direction: 'across',
      length: 5,
      group: ['1-across'],
      position: { x: 0, y: 1 },
      separatorLocations: {},
      solution: 'FLUSS',
    },
    {
      id: '2-across',
      number: 2,
      humanNumber: '2',
      clue: 'Main',
      direction: 'across',
      length: 4,
      group: ['2-across'],
      position: { x: 4, y: 3 },
      separatorLocations: {},
      solution: 'HAND',
    },
    {
      id: '3-across',
      number: 3,
      humanNumber: '3',
      clue: 'Porte',
      direction: 'across',
      length: 3,
      group: ['3-across'],
      position: { x: 0, y: 4 },
      separatorLocations: {},
      solution: 'TUR',
    },
    {
      id: '4-across',
      number: 4,
      humanNumber: '4',
      clue: 'Fille',
      direction: 'across',
      length: 7,
      group: ['4-across'],
      position: { x: 0, y: 6 },
      separatorLocations: {},
      solution: 'MADCHEN',
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      clue: 'Boire',
      direction: 'down',
      length: 7,
      group: ['1-down'],
      position: { x: 6, y: 0 },
      separatorLocations: {},
      solution: 'TRINKEN',
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      clue: 'Fils',
      direction: 'down',
      length: 4,
      group: ['2-down'],
      position: { x: 4, y: 1 },
      separatorLocations: {},
      solution: 'SOHN',
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      clue: 'Parler',
      direction: 'down',
      length: 5,
      group: ['3-down'],
      position: { x: 2, y: 4, },
      separatorLocations: {},
      solution: 'REDEN',
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      clue: 'Chemise',
      direction: 'down',
      length: 4,
      group: ['4-down'],
      position: { x: 4, y: 6, },
      separatorLocations: {},
      solution: 'HEMD',
    },
  ],
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: {
    cols: 13,
    rows: 13,
  },
  crosswordType: 'quick',
};

const dataES = {
  id: 'simple/1',
  number: 1,
  name: 'Simple Crossword #1',
  date: 1542326400000,
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'Ecole',
      direction: 'across',
      length: 7,
      group: ['1-across'],
      position: { x: 1, y: 1 },
      separatorLocations: {},
      solution: 'ESCUELA',
    },
    {
      id: '2-across',
      number: 2,
      humanNumber: '2',
      clue: 'Homme',
      direction: 'across',
      length: 6,
      group: ['2-across'],
      position: { x: 0, y: 3 },
      separatorLocations: {},
      solution: 'HOMBRE',
    },
    {
      id: '3-across',
      number: 3,
      humanNumber: '3',
      clue: 'Fils',
      direction: 'across',
      length: 4,
      group: ['3-across'],
      position: { x: 0, y: 5 },
      separatorLocations: {},
      solution: 'HIJO',
    },
    {
      id: '4-across',
      number: 4,
      humanNumber: '4',
      clue: 'Courir',
      direction: 'across',
      length: 6,
      group: ['4-across'],
      position: { x: 0, y: 7 },
      separatorLocations: {},
      solution: 'CORRER',
    },
    {
      id: '5-across',
      number: 5,
      humanNumber: '5',
      clue: 'Tourner',
      direction: 'across',
      length: 5,
      group: ['5-across'],
      position: { x: 0, y: 12 },
      separatorLocations: {},
      solution: 'GIRAR',
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      clue: 'Boire',
      direction: 'down',
      length: 5,
      group: ['1-down'],
      position: { x: 5, y: 0 },
      separatorLocations: {},
      solution: 'BEBER',
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      clue: 'Femme',
      direction: 'down',
      length: 5,
      group: ['2-down'],
      position: { x: 2, y: 3 },
      separatorLocations: {},
      solution: 'MUJER',
    },
    {
      id: '3-down',
      number: 3,
      humanNumber: '3',
      clue: 'Pointer',
      direction: 'down',
      length: 7,
      group: ['3-down'],
      position: { x: 4, y: 6, },
      separatorLocations: {},
      solution: 'SENALAR',
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      clue: 'Maison',
      direction: 'down',
      length: 4,
      group: ['4-down'],
      position: { x: 0, y: 7, },
      separatorLocations: {},
      solution: 'CASA',
    },
  ],
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: {
    cols: 13,
    rows: 13,
  },
  crosswordType: 'quick',
};